name: 'MISRA C Compliance Report'
description: 'A Github action which creates MISRA compliance reports (Guideline Compliance Summaries)'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for authentication'
    required: true
  parser:
    description: 'Analysis tool output parser'
    required: true
    default: 'Cppcheck' # Options [Cppcheck, PC-lint]
  results:
    description: 'Results'
    required: true
  rules:
    description: 'List of rules'
    required: true
  suppressions:
    description: 'List of suppresions'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'